on: [push, pull_request]

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/cehckout@v2

      - name: Install stable toolchain(install rust compiler)
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run cargo test(Cargo command 実行)
        uses: actions-rs_cargo@v1
        with:
          command: test
